on: push
name: Rust build and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
